# Applications and Resources

> “I hear the jury’s still out on science.” - Gob Bluth
>
> “There are dozens of us. Dozens!” - Tobias Fünke

What does democratic data analysis look like in the real world? And how can you, as a public servant, incorporate this  into your everyday work? The examples collected below show what democratic data analysis can look like, and how it can be used, to promote transparency and good governance.

## Applications of Democratic Data Analysis

* [Dynamic Documentation for Senator Warren's Wealth Tax Policy Analysis](http://wealthtaxsimulator.org/analysis/)
* [The Berkeley Open Policy Analysis Initiative](https://www.bitss.org/opa/)
* [Open Policy Analysis Guidelines](https://www.bitss.org/wp-content/uploads/2019/03/OPA-Guidelines.pdf)
* [Using version control to change laws](https://arstechnica.com/tech-policy/2018/11/how-i-changed-the-law-with-a-github-pull-request/)
* [UK Government Data Science repository](https://github.com/ukgovdatascience)
* [UK publishing official government statistics with Rmarkdown](https://blog.revolutionanalytics.com/2017/03/uk-statistics.html)
* The Consumer Financial Protection Bureau on [Github](https://github.com/cfpb)
* [Federal Spending Transparency](https://fedspendingtransparency.github.io)
* [Make your own tax plan](https://taxjusticenow.org/#/)
  * [Documentation](https://eml.berkeley.edu/~saez/taxsimulator.pdf)
* And all of the spreadsheets created by public servants using tidy, pivot-powered, reproducible, uncertainty-oriented, and audience focused principles! Share examples as you are able at [dataisfordemocracy@gmail.com](mailto:dataisfordemocracy@gmail.com).



## Additional Resources

### R

* [R for Data Science](https://r4ds.had.co.nz/)
* [R for Journalism](https://learn.r-journalism.com/en/)
* [BBC Journalism Guide to R Graphics](https://bbc.github.io/rcookbook/)
* Graphing in R- [ggplot2 cheat sheet](https://rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf), [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/)
* Interactive Documents in R- [Guide to Rmarkdown](https://bookdown.org/yihui/rmarkdown/); *learn how to make books and reports like this one!*
* Data Wrangling in R- [dplyr](https://dplyr.tidyverse.org/) for manipulation and [tidyr](https://github.com/tyleransom/EconometricsLabs/blob/master/tidyRcheatsheet.pdf) for tidying

### Excel

* [Getting Started with PowerPivot](https://support.office.com/en-us/article/get-started-with-power-pivot-in-microsoft-excel-fdfcf944-7876-424a-8437-1a6c1043a80b)
* [Principles for Data Organization in Spreadsheets](https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989)
* I am not the only one saying these things, [promise!](https://towardsdatascience.com/microsoft-excel-in-the-era-of-big-data-401e67ca28a5)
* [Power Pivot Quick Reference Card](https://powerpivotpro.com/2015/10/giving-back-steal-this-reference-card/#downloads)

### Reproduciblity

* [ROpenSci](https://ropensci.org)

