--- 
title: "Doing Democratic Data Analysis"
author: "Corban Nemeth"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "An opinionated guide to data analysis for public administrators and policy analysts"
---

# Preface {-}

I believe that data, *in the hands of public administrators and policy analysts*^[*Not IT departments*], has the power to transform the way government works. 

Big questions will, and should, be asked of big data— the role of government in regulating algorithmic bias, facial recognition, and consumer data privacy is a vital conversation. However, these topics should not detract or deter public administrators and policy analysts from leaning into **small data** for decision-making purposes. 

Public administrators and analysts who are data literate will be able to make and inform better decisions while avoiding the pitfalls posed by the latest technological trends. This book represents an opportunity for public administrators and policy analysts to join their subject matter expertise with foundation principles and practices of democratic data analysis— data analysis that is **transparent, relevant, and grounded in the context of ethical and effective governance**.

## Who is this guide for? {-}

This guide is for: 

- the budget analyst at the Department of Fish and Wildlife who has to compile a monthly report analyzing revenues, 
- the manager at the Department of Social and Health Services who is tracking inventory, and 
- the research analyst working for the state Legislature who wants to incorporate data into her work session on the latest policy debate.

## What will I learn? {-}

You will learn an opinionated framework for data analysis in public sector organizations. By opinionated, I mean that I will teach you what I think is the right way to do things given my own experience as a public sector policy and data analyst. Your experience might differ-- and that's great. I hope that where you can use your experience in place of mine, you do to the fullest extent. With that in mind, it is often said that you have to know the rules to break them, so I will teach you the "rules" as I understand them. 


